# netlify.toml 

[build]
  command = "npm run build"
  publish = "dist-client"
  functionsSource = "app/serverless"
  functions = "dist-serverless"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200